// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"ts-server/apis/v1"
	"ts-server/repositories"
	"ts-server/services"
)

// Injectors from container.go:

func CreateQuestionController() *apis.QuestionController {
	questionRepository := repositories.NewQuestionRepository()
	questionService := services.NewQuestionService(questionRepository)
	questionController := apis.NewQuestionController(questionService)
	return questionController
}
